### ISSUE TITLE
Broken FontResources?

### ISSUE THREAD

**Issue by stefanofornari** [palexdev/MFXResources#1]
Some values in FontResources seem to be incorrect. For example:

MaterialFX: HYPHEN("mfx-hyphen", '\uE942') -> correct
MFXResources: HYPHEN("mfx-hyphen", '\uE951') -> incorrect

It results in:

![image](https://user-images.githubusercontent.com/43138/212461480-41421680-fd93-48ab-81fe-a0f1dc01e7c9.png)

**Comment by palexdev** [comment]
Resources here have been updated
MaterialFX still uses it's own assets

**Comment by stefanofornari** [comment]
It still does not work. Here is the code I am using:

package ste.w3.easywallet.ui;


```
import io.github.palexdev.materialfx.font.MFXFontIcon;
import io.github.palexdev.mfxresources.font.FontResources;

/**
 *
 */
public enum SortingIcons {
    ASCENDING(FontResources.CARET_UP.getDescription()),
    DESCENDING(FontResources.CARET_DOWN.getDescription()),
    NONE(FontResources.HYPHEN.getDescription());

    public final String symbol;

    SortingIcons(final String symbol) {
        System.out.println("symbol: " + symbol);
        this.symbol = symbol;
    }

    public MFXFontIcon newIcon() {
        return new MFXFontIcon(symbol);
    }
}


```

I see the icon above...

**Comment by palexdev** [comment]
I'll investigate
Use an older version In the meantime

**Comment by stefanofornari** [comment]
yeah, it looks like if I use VirtualizedFX 11.8.1 it works 

![image](https://user-images.githubusercontent.com/43138/212466851-b8837964-e6de-401d-b363-0ec070d17bb2.png)

But it might be the way I built VirtualizedFX from source.... I'll investigate it as well...

**Comment by stefanofornari** [comment]
update: I confirm that even using the jar produced by gradle the issue is still there.

**Comment by palexdev** [comment]
@stefanofornari Found the issue, if you use both MaterialFX and MFXResources then the two will be in conflict
I'll update MaterialFX with these ones and push a new minor version

**Comment by stefanofornari** [comment]
Thanks for fixing it! Can you please release also 11.14.0-EA4? There is in there io.github.palexdev.materialfx.controls.MFXTitledPane which is used by VirtualTable in VirtualizedFX.

**Comment by palexdev** [comment]
I can't release it as it's unstable, I believe there are issues with the demo, maybe something is broken
I'll have to check it thoroughly first

**Comment by stefanofornari** [comment]
Sorry, you are right. It was a left-over in the FXML (I was importing it although not using it). And you also right it is used in demo's FXMLs in VirtualizedFX.
